services:
  mariadb-container:
    build:
      context: ./requirements/mariadb/
    container_name: mariadb-container
    expose:
      - "3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception
    environment:
      C_DATABASE_NAME : $C_DATABASE_NAME
      C_DATABASE_USER_NAME : $C_DATABASE_USER_NAME
      C_DATABASE_USER_PASS : $C_DATABASE_USER_PASS
    restart: always


  wordpress-container:
    build: 
      context: ./requirements/wordpress/
    container_name: wordpress-container
    expose:
      - "9000" 
    volumes:
      - wordpress-data:/var/www/wordpress
    depends_on : 
      - mariadb-container
    networks:
      - inception
    restart: always
    environment:
      ADMIN_USER: $ADMIN_USER
      ADMIN_PASSWORD: $ADMIN_PASSWORD
      ADMIN_EMAIL: $ADMIN_EMAIL
      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: $WORDPRESS_TABLE_PREFIX
      WORDPRESS_DEBUG: $WORDPRESS_DEBUG

  nginx-container:
    build: 
      context: ./requirements/nginx/
    container_name: nginx-container
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/wordpress
    depends_on:
      - wordpress-container
    networks:
      - inception
    restart: always

volumes:
    nginx-data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/zel-khad/data/web
    wordpress-data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/zel-khad/data/web
    mariadb-data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/zel-khad/data/database

networks:
  inception:
    driver: bridge
