services:

  mariadb-container:
    build:
      context: ./requirements/mariadb/
    container_name: mariadb-container
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: zakariae
      MYSQL_PASSWORD: password1
      MYSQL_ROOT_PASSWORD: rootpassword

  wordpress-container:
    build: ./requirements/wordpress/
    container_name: wordpress-container
    volumes:
      - wordpress-data:/var/www/wordpress
    depends_on:
      - mariadb-container
    networks:
      - inception
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: mariadb-container
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: zakariae
      WORDPRESS_DB_PASSWORD: password1

  nginx-container:
    build: ./requirements/nginx/
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - wordpress-data:/var/www/wordpress
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress-container
    networks:
      - inception
    restart: unless-stopped

volumes:
  wordpress-data:
  mariadb-data:

networks:
  inception:
    driver: bridge
