services:
  mariadb-container:
    build:
      context: ./requirements/mariadb/
    container_name: mariadb-container
    expose:
      - "3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception
    # environment:
    #   MYSQL_DATABASE: wordpress
    #   MYSQL_USER: zakariae
    #   MYSQL_PASSWORD: password1
    #   MYSQL_ROOT_PASSWORD: rootpassword
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  wordpress-container:
    build: 
      context: ./requirements/wordpress/
    container_name: wordpress-container
    expose:
      - "9000" 
    volumes:
      - wordpress-data:/var/www/wordpress
    depends_on:
      mariadb-container:
        condition: service_healthy
    networks:
      - inception
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: $WORDPRESS_DB_HOST
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_TABLE_PREFIX: $WORDPRESS_TABLE_PREFIX
      WORDPRESS_DEBUG: $WORDPRESS_DEBUG

  nginx-container:
    build: 
      context: ./requirements/nginx/
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - wordpress-data:/var/www/wordpress
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      wordpress-container:
        condition: service_started
    networks:
      - inception
    restart: unless-stopped

volumes:
  wordpress-data:
    driver: local
  mariadb-data:
    driver: local

networks:
  inception:
    driver: bridge
    # ipam:
    #   config:
    #     - subnet: 172.20.0.0/16



