
services:
  wordpress-container:
    build: ./requirements/wordpress/
    container_name: wordpress-container
    expose:
      - "9000"
    volumes:
      - wordpress-data:/var/www/wordpress
    restart: unless-stopped

  nginx-container:
    build: ./requirements/nginx/
    container_name: nginx-container
    ports:
      - "8081:80"
    volumes:
      - wordpress-data:/var/www/wordpress
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress-container
    restart: unless-stopped

volumes:
  wordpress-data:
