
services:
  mariadb-container:
    build: ./requirements/mariadb/
    container_name: mariadb-container
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=%MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=wp_pass
    networks:
      - inception
    restart: unless-stopped
  wordpress-container:
    build: ./requirements/wordpress/
    container_name: wordpress-container
    volumes:
      - wordpress-data:/var/www/wordpress
    depends_on:
      - mariadb-container
    networks:
      - inception
    restart: unless-stopped

  nginx-container:
    build: ./requirements/nginx/
    container_name: nginx-container
    ports:
      - "8081:80"
    volumes:
      - wordpress-data:/var/www/wordpress
      - ./requirements/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress-container
    networks:
      - inception
    restart: unless-stopped

volumes:
  wordpress-data:
  mariadb-data:

networks:
  inception:
    driver: bridge
