services:
  nginx-container:
    build: ./requirements/nginx/
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./requirements/nginx/html:/usr/share/nginx/html
    restart: unless-stopped

