services:
  mariadb-container:
    build: ./requirements/mariadb/
    container_name: mariadb-container
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=2001
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=wp_pass
    networks:
      - inception
    restart: unless-stopped

  wordpress-container:
    build: ./requirements/wordpress/
    container_name: wordpress-container
    volumes:
      - wordpress-data:/var/www/wordpress
    depends_on:
      - mariadb-container
    networks:
      - inception
    restart: unless-stopped

  nginx-container:
    build: ./requirements/nginx/
    container_name: nginx-container
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/wordpress
    depends_on:
      - wordpress-container
    networks:
      - inception
    restart: unless-stopped

volumes:
  wordpress-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/john/data/wordpress

  mariadb-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/john/data/mariadb

networks:
  inception:
    driver: bridge
