services:
  adminer-container:
    build: ./requirements/bonus/Adminer/
    container_name : adminer-container
    networks:
      - inception
    depends_on:
      wordpress-container:
        condition: service_healthy
    restart: always

  mariadb-container:
    build:
      context: ./requirements/mariadb/
    container_name: mariadb-container
    expose:
      - "3306"
    volumes:
        - mariadb-data:/var/lib/mysql
    networks:
      - inception
    env_file:
      - .env
    restart: always

  wordpress-container:
    build: 
      context: ./requirements/wordpress/
    container_name: wordpress-container
    expose:
      - "9000" 
    volumes:
      - wordpress-data:/var/www/html
    depends_on : 
      - redis-container
      - mariadb-container
    networks:
      - inception
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 9000"]
      interval: 5s
      timeout: 5s
      retries: 5

  nginx-container:
    build: 
      context: ./requirements
      dockerfile: nginx/Dockerfile
    container_name: nginx-container
    ports:
      - "443:443"
    volumes:
      - wordpress-data:/var/www/html
    depends_on:
      wordpress-container:
        condition: service_healthy
    networks:
      - inception
    restart: always

  redis-container:
    build: ./requirements/bonus/redis/
    container_name : redis-container
    volumes:
      - wordpress-data:/var/www/html
    ports:
      - "6379:6379"
    networks:
      - inception
    restart: always
  
  ftp-container:
    build: ./requirements/bonus/ftp/
    container_name : ftp-container
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - wordpress-data:/var/www/html
    networks:
      - inception
    env_file:
      - .env
    restart: always

  msmtp-container:
    env_file:
      - .env
    build: ./requirements/bonus/msmtp
    container_name: msmtp-container
    ports:
      - "25:25"
    networks:
      - inception
    restart: always

  rsyslog-container:
    env_file:
      - .env
    build: ./requirements/bonus/rsyslog
    container_name: rsyslog-container
    ports:
      - "514:514/udp"
    volumes:
      - ./logs:/var/log/remote
    networks:
      - inception
    restart: always

    
volumes:
    nginx-data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/zel-khad/data/web
    wordpress-data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/zel-khad/data/web
    mariadb-data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/zel-khad/data/database

networks:
  inception:
    driver: bridge